# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: node.js CI

on:
  workflow_call:
    secrets:
      REPO_SSH_KEY:
        required: true
      NPM_LOGIN_NAME: 
        required: false
      NPM_EMAIL:
        required: false
      PAT_PACKAGE:
        required: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      env: 
        NPM_LOGIN_NAME = ${{ secrets.NPM_LOGIN_NAME }}
    - uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with: 
        key: ${{ secrets.REPO_SSH_KEY }}
        name: id_ed25519
        known_hosts: unnecessary
        if_key_exists: replace

    # Install npm for the given node.js version
    - name: Build for Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Login to npm registry if required
      if: env.NPM_LOGIN_NAME != null
      run: npm login --scope=@${{ secrets.NPM_LOGIN_NAME}} --registry=https://npm.pkg.github.com << ${{secrets.NPM_LOGIN_NAME}} << ${{secrets.PAT_PACKAGE}} << ${{secrets.NPM_EMAIL}}

    - name: Install packages
      run: |
        npm ci
        npm run build --if-present
    
    - name: Test the app
      uses: ospfranco/gh-jester@latest
      with:
        post-comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_CONTEXT: ${{ toJson(github) }}

    # Upload the test results
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: coverage/lcov-report
